image: Visual Studio 2017

before_build:
  - nuget restore -NonInteractive
  - nuget restore iMobileDevice.Generator\packages.config -SolutionDirectory .  -NonInteractive
  - dotnet restore
  - if not exist ext mkdir ext
  - choco install -y wget
  - download.cmd

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - ext -> download.cmd
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'  # NuGet package for .NET Core

build_script:
  - msbuild iMobileDevice.Generator\iMobileDevice.Generator.csproj /p:Configuration=Debug /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - iMobileDevice.Generator\bin\x86\Debug\iMobileDevice.Generator.exe . .\iMobileDevice-net
  - dotnet build imobiledevice-net\iMobileDevice-net.csproj
  - dotnet pack imobiledevice-net\iMobileDevice-net.csproj --version-suffix r%APPVEYOR_BUILD_NUMBER% -c Release
  - dotnet build runtime.win7-x64.vcruntime140\runtime.win7-x64.vcruntime140.csproj
  - dotnet pack runtime.win7-x64.vcruntime140\runtime.win7-x64.vcruntime140.csproj -c Release
  - dotnet build runtime.win7-x86.vcruntime140\runtime.win7-x86.vcruntime140.csproj
  - dotnet pack runtime.win7-x86.vcruntime140\runtime.win7-x86.vcruntime140.csproj -c Release
  - 7z x imobiledevice-net\bin\Release\imobiledevice-net.1.2.1-r%APPVEYOR_BUILD_NUMBER%.nupkg -ozip\
  - 7z a -tzip libimobiledevice.1.2.1-r%APPVEYOR_BUILD_NUMBER%-win-x86.zip -r zip\runtimes\win7-x86\native\
  - 7z a -tzip libimobiledevice.1.2.1-r%APPVEYOR_BUILD_NUMBER%-win-x64.zip -r zip\runtimes\win7-x64\native\

on_success:
  - ps: Push-AppVeyorArtifact imobiledevice-net\bin\Release\imobiledevice-net.1.2.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg
  - ps: Push-AppVeyorArtifact runtime.win7-x64.vcruntime140\bin\Release\runtime.win7-x64.vcruntime140.14.0.24406.1.nupkg
  - ps: Push-AppVeyorArtifact runtime.win7-x86.vcruntime140\bin\Release\runtime.win7-x86.vcruntime140.14.0.24406.1.nupkg
  - ps: Push-AppVeyorArtifact runtime.win7-x86.vcruntime140\bin\Release\runtime.win7-x86.vcruntime140.14.0.24406.1.nupkg
  - ps: Push-AppVeyorArtifact libimobiledevice.1.2.1-r$($env:APPVEYOR_BUILD_NUMBER)-win-x64.zip
  - ps: Push-AppVeyorArtifact libimobiledevice.1.2.1-r$($env:APPVEYOR_BUILD_NUMBER)-win-x86.zip

nuget:
  project_feed: true
  account_feed: true