image: Visual Studio 2017

environment:
  VCPKG_ROOT: C:\tools\vcpkg-libimobiledevice

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

before_build:
  - vcpkg version
  - git version
# Work around https://stackoverflow.com/questions/50093771/git-clone-warning-failed-to-restrict-file-handles
  - choco install git
  - git version
  - ps: if( -not (Test-Path $env:VCPKG_ROOT -PathType Container)) { git clone -q --depth 1 -b ports/libimobiledevice https://github.com/libimobiledevice-win32/vcpkg $env:VCPKG_ROOT; Write-Host "Cloned repo to $env:VCPKG_ROOT" } else { Write-Host "$env:VCPKG_ROOT exists, not cloning repository." }
  - cmd: git --git-dir %VCPKG_ROOT%\.git --work-tree %VCPKG_ROOT% fetch origin
  - cmd: git --git-dir %VCPKG_ROOT%\.git --work-tree %VCPKG_ROOT% reset --hard origin/ports/libimobiledevice
  - cmd: "%VCPKG_ROOT%\\bootstrap-vcpkg.bat"
  - cmd: "%VCPKG_ROOT%\\vcpkg version"
  - cmd: "%VCPKG_ROOT%\\vcpkg integrate install"

# Make sure we always compile 'our' packages from scratch
  - cmd: "%VCPKG_ROOT%\\vcpkg remove libplist:x86-windows libusbmuxd:x86-windows libimobiledevice:x86-windows usbmuxd:x86-windows ideviceinstaller:x86-windows libideviceactivation:x86-windows"
  - cmd: "%VCPKG_ROOT%\\vcpkg remove libplist:x64-windows libusbmuxd:x64-windows libimobiledevice:x64-windows usbmuxd:x64-windows ideviceinstaller:x64-windows libideviceactivation:x64-windows"
  - cmd: "%VCPKG_ROOT%\\vcpkg install --head libplist:x86-windows libusbmuxd:x86-windows libimobiledevice:x86-windows usbmuxd:x86-windows ideviceinstaller:x86-windows libideviceactivation:x86-windows"
  - cmd: "%VCPKG_ROOT%\\vcpkg install --head libplist:x64-windows libusbmuxd:x64-windows libimobiledevice:x64-windows usbmuxd:x64-windows ideviceinstaller:x64-windows libideviceactivation:x64-windows"
  - cmd: "%VCPKG_ROOT%\\vcpkg update"

  - dotnet restore
  - dotnet restore iMobileDevice.Generator\iMobileDevice.Generator.csproj
  - if not exist ext mkdir ext
  - choco install -y wget
  - download.cmd

cache:
  - C:\tools\vcpkg-libimobiledevice

build_script:
  - cd iMobileDevice.Generator
  - dotnet run . ..\iMobileDevice-net
  - cd ..
  - dotnet build imobiledevice-net\iMobileDevice-net.csproj
  - dotnet pack imobiledevice-net\iMobileDevice-net.csproj -c Release
  - dotnet build runtime.win7-x64.vcruntime140\runtime.win7-x64.vcruntime140.csproj
  - dotnet pack runtime.win7-x64.vcruntime140\runtime.win7-x64.vcruntime140.csproj -c Release
  - dotnet build runtime.win7-x86.vcruntime140\runtime.win7-x86.vcruntime140.csproj
  - dotnet pack runtime.win7-x86.vcruntime140\runtime.win7-x86.vcruntime140.csproj -c Release

  # Create a zip archive for libimobiledevice-win32
  - 7z x imobiledevice-net\bin\Release\imobiledevice-net.*.nupkg -ozip\
  - 7z a -tzip libimobiledevice.1.2.1-r%APPVEYOR_BUILD_NUMBER%-win-x86.zip .\zip\runtimes\win-x86\native\*
  - 7z a -tzip libimobiledevice.1.2.1-r%APPVEYOR_BUILD_NUMBER%-win-x64.zip .\zip\runtimes\win-x64\native\*

  # This should help the tests locate libimobiledevice and friends
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\zip\runtimes\win-x64\native
  - echo %PATH%
  - dir %APPVEYOR_BUILD_FOLDER%\zip\runtimes\win-x64\native
  - dotnet test iMobileDevice.Generator.Tests\iMobileDevice.Generator.Tests.csproj
  - dotnet test iMobileDevice.Tests\iMobileDevice.Tests.csproj

artifacts:
  - path: imobiledevice-net\bin\Release\imobiledevice-net.*.nupkg
    name: imobiledevice-net
  - path: runtime.win7-x64.vcruntime140\bin\Release\runtime.win7-x64.vcruntime140.14.*.nupkg
  - path: runtime.win7-x86.vcruntime140\bin\Release\runtime.win7-x86.vcruntime140.14.*.nupkg
  - path: libimobiledevice.*-win-x64.zip
  - path: libimobiledevice.*-win-x86.zip

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: Ato5KuMaGhWf+Fj6q7FYLbJhnzFBZcBu71GWLtq8d4X4Yrd2iXp+wpf6WXEv5myb
  skip_symbols: true
  artifact: imobiledevice-net