before_build:
  - nuget restore
  - nuget restore iMobileDevice.Generator\packages.config -SolutionDirectory .
  - dotnet restore

build_script:
  - msbuild iMobileDevice.Generator\iMobileDevice.Generator.csproj /p:Configuration=Debug /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - iMobileDevice.Generator\bin\x86\Debug\iMobileDevice.Generator.exe . .\iMobileDevice-net
  - msbuild iMobileDevice-net\iMobileDevice.csproj /p:Configuration=Debug /p:Platform=AnyCPU /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

on_success:
  - ps: .\UpdateNuGetFile.ps1 -Build $ENV:APPVEYOR_BUILD_NUMBER
  - cmd: cd iMobileDevice-net
  - cmd: nuget pack imobiledevice-net.out.nuspec
  - cmd: appveyor PushArtifact imobiledevice-net.1.2.0.%APPVEYOR_BUILD_NUMBER%.nupkg

nuget:
  project_feed: true
  account_feed: true